[book]
authors = ["Nur"]
language = "en"
multilingual = false
src = "src"
title = "Trivial File Transfer Protocol"

[output.html]
default-theme = "ayu"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/nurmohammed840/tftp.rs"
additional-css = ["src/assets/mdbook-admonish.css", "src/assets/custom.css"]

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"
